// <auto-generated />
using System;
using Basarsoft.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Basarsoft.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seq_permissions");

            modelBuilder.HasSequence<int>("seq_role_permissions");

            modelBuilder.HasSequence<int>("seq_roles");

            modelBuilder.HasSequence<int>("seq_tbl_geo_authorization");

            modelBuilder.HasSequence<int>("seq_tbl_line");

            modelBuilder.HasSequence<int>("seq_tbl_location_analysis");

            modelBuilder.HasSequence<int>("seq_tbl_location_analysis_criterion");

            modelBuilder.HasSequence<int>("seq_tbl_poi");

            modelBuilder.HasSequence<int>("seq_tbl_poi_category");

            modelBuilder.HasSequence<int>("seq_tbl_point");

            modelBuilder.HasSequence<int>("seq_tbl_polygon");

            modelBuilder.HasSequence<int>("seq_tbl_province");

            modelBuilder.HasSequence<int>("seq_user_permissions");

            modelBuilder.HasSequence<int>("seq_user_roles");

            modelBuilder.HasSequence<int>("seq_users");

            modelBuilder.Entity("Basarsoft.Api.Models.GeoAuthorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_geo_authorization')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_geo_authorization");

                    b.HasIndex("RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_tbl_geo_authorization_role_id")
                        .HasFilter("role_id IS NOT NULL AND NOT is_deleted");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tbl_geo_authorization_user_id")
                        .HasFilter("user_id IS NOT NULL AND NOT is_deleted");

                    b.ToTable("tbl_geo_authorization", null, t =>
                        {
                            t.HasCheckConstraint("ck_tbl_geo_authorization_target", "num_nonnulls(user_id, role_id) = 1");
                        });
                });

            modelBuilder.Entity("Basarsoft.Api.Models.LineFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_line')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(LineString,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_line");

                    b.HasIndex("ModifiedUserId")
                        .HasDatabaseName("ix_tbl_line_modified_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tbl_line_user_id");

                    b.ToTable("tbl_line", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.LocationAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_location_analysis')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("integer")
                        .HasColumnName("province_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_location_analysis");

                    b.HasIndex("ModifiedUserId")
                        .HasDatabaseName("ix_tbl_location_analysis_modified_user_id");

                    b.HasIndex("ProvinceId")
                        .HasDatabaseName("ix_tbl_location_analysis_province_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tbl_location_analysis_user_id");

                    b.ToTable("tbl_location_analysis", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.LocationAnalysisCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_location_analysis_criterion')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_tbl_location_analysis_criterion");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tbl_location_analysis_criterion_category_id");

                    b.HasIndex("ModifiedUserId")
                        .HasDatabaseName("ix_tbl_location_analysis_criterion_modified_user_id");

                    b.HasIndex("AnalysisId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_tbl_location_analysis_criterion_analysis_id_category_id");

                    b.ToTable("tbl_location_analysis_criterion", null, t =>
                        {
                            t.HasCheckConstraint("ck_tbl_location_analysis_criterion_weight", "weight BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Basarsoft.Api.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_permissions')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_poi')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("close_time");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("open_time");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_poi");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tbl_poi_category_id");

                    b.HasIndex("ModifiedUserId")
                        .HasDatabaseName("ix_tbl_poi_modified_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tbl_poi_user_id");

                    b.ToTable("tbl_poi", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.PoiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_poi_category')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IconKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_poi_category");

                    b.HasIndex("ModifiedUserId")
                        .HasDatabaseName("ix_tbl_poi_category_modified_user_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_tbl_poi_category_parent_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tbl_poi_category_user_id");

                    b.ToTable("tbl_poi_category", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.PointFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_point')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_point");

                    b.HasIndex("ModifiedUserId")
                        .HasDatabaseName("ix_tbl_point_modified_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tbl_point_user_id");

                    b.ToTable("tbl_point", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.PolygonFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_polygon')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tbl_polygon");

                    b.HasIndex("ModifiedUserId")
                        .HasDatabaseName("ix_tbl_polygon_modified_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tbl_polygon_user_id");

                    b.ToTable("tbl_polygon", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_tbl_province')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geom");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tbl_province");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tbl_province_name");

                    b.ToTable("tbl_province", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_roles')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_role_permissions')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_permissions_role_id_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_users')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_user_permissions')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_user_permissions_permission_id");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_permissions_user_id_permission_id");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('seq_user_roles')")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Basarsoft.Api.Models.GeoAuthorization", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tbl_geo_authorization_roles_role_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tbl_geo_authorization_users_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.LineFeature", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .HasConstraintName("fk_tbl_line_users_modified_user_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_line_users_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.LocationAnalysis", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .HasConstraintName("fk_tbl_location_analysis_users_modified_user_id");

                    b.HasOne("Basarsoft.Api.Models.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tbl_location_analysis_tbl_province_province_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_location_analysis_users_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.LocationAnalysisCriterion", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.LocationAnalysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_location_analysis_criterion_tbl_location_analysis_analy");

                    b.HasOne("Basarsoft.Api.Models.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_location_analysis_criterion_tbl_poi_category_category_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .HasConstraintName("fk_tbl_location_analysis_criterion_users_modified_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.Poi", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_poi_tbl_poi_category_category_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .HasConstraintName("fk_tbl_poi_users_modified_user_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_poi_users_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.PoiCategory", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .HasConstraintName("fk_tbl_poi_category_users_modified_user_id");

                    b.HasOne("Basarsoft.Api.Models.PoiCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tbl_poi_category_tbl_poi_category_parent_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_poi_category_users_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.PointFeature", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .HasConstraintName("fk_tbl_point_users_modified_user_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_point_users_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.PolygonFeature", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .HasConstraintName("fk_tbl_polygon_users_modified_user_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tbl_polygon_users_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.RolePermission", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Basarsoft.Api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.UserPermission", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_permissions_permission_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");
                });

            modelBuilder.Entity("Basarsoft.Api.Models.UserRole", b =>
                {
                    b.HasOne("Basarsoft.Api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Basarsoft.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
